name: Android UI tests

on: pull_request

jobs:
  build:
    name: android_ui_tests
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: 29
            script: ./gradlew app:connectedCheck
